application: webapp2
version: 1
runtime: python27
api_version: 1
threadsafe: true

derived_file_type:
- python_precompiled

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /test.*
  script: test.py

- url: /.*
  script: main.app
